spring:

  data:
    redis:
      port: 6379
      host: 13.124.152.41
      password: spot1234!

  datasource:
    url: jdbc:mysql://spot-db.c4xdcqwxcink.ap-northeast-2.rds.amazonaws.com:3306/spot
    username: admin
    password: spot1234!

  jpa:
    hibernate:
      ddl-auto: update

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 8e766924532fe4a01ff93f1aa3d56b88
            client-secret: Qk7XkVtgAEATTEDxHzHxAP25L7COVsDk
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  spring:
    servlet:
      multipart:
        file-size-threshold: 1MB
        location: C:/Temp
        max-file-size: 100MB
        max-request-size: 100MB



jwt:
  secretKey: dsdfnndfgjnfnjerhrgndfjvdfj3y4t64584545455151612ggjfjjfjvjf

  access:
    expiration: 3600000 # 1??(60?) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> ??) * 14(2?))
    header: Authorization-refresh
